### ISSUE TITLE
update peer dependencies to include graphql 15

### ISSUE THREAD

**Issue by mobsean** [zapier/apollo-server-integration-testing#13]
Hi, 
please update peer-dependencies in package.json.

After 
`npm i -D apollo-server-integration-testing`

I recieved:

>npm ERR! code ERESOLVE
>npm ERR! ERESOLVE unable to resolve dependency tree
>npm ERR!
>npm ERR! Found: graphql@15.5.0
npm ERR! node_modules/graphql
....................
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev apollo-server-integration-testing@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: graphql@14.7.0
npm ERR! node_modules/graphql
npm ERR!   peer graphql@"^0.12.0 || ^0.13.0 || ^14.0.0" from apollo-server-integration-testing@2.3.0
npm ERR!   node_modules/apollo-server-integration-testing
npm ERR!     dev apollo-server-integration-testing@"*" from the root project

**Comment by vitorbal** [comment]
@mobsean mind opening a PR for that? I'd be glad to review it
