### ISSUE TITLE
How to add more context object besides req and res?

### ISSUE THREAD

**Issue by jasonlimantoro** [zapier/apollo-server-integration-testing#17]
Let's say that this is the actual code:
```ts
import imageServce from './services/imageService';
const apolloServer = new ApolloServer({
        // ... other options
	context: ({ req, res } => ({ req, res, imageService })),
});
```
How to mock the `imageService` ?

**Comment by vitorbal** [comment]
Hey @jasonlimantoro, that will depend on which test framework you use. This library auto-mocks the `req` and `res` objects for convenience to help you get started quickly, but doesn't make any other assumptions about mocking.

To illustrate, you could mock `imageService` in your example by mocking the fetch request using [fetch-mock](https://github.com/wheresrhys/fetch-mock). Or, if you're using [Jest](https://jestjs.io/), you could mock the entire module with [jest.mock](https://jestjs.io/docs/mock-functions#mocking-modules).

**Comment by vitorbal** [comment]
Closing since it doesn't look like there's anything actionable here. Let me know if you disagree!
