### ISSUE TITLE
Session type

### ISSUE THREAD

**Issue by sixnames** [zapier/apollo-server-integration-testing#7]
Hi! Thank you for amazing tool. Can I ask you for small improvement? I have issue with types in Session interface. It is not have required method types.
Your interface
```typescript
    export interface Session {
        [key: string]: string;
    }
```

Interface from express-session
```typescript
    interface Session extends SessionData {
      id: string;
      regenerate(callback: (err: any) => void): void;
      destroy(callback: (err: any) => void): void;
      reload(callback: (err: any) => void): void;
      save(callback: (err: any) => void): void;
      touch(): void;
      cookie: SessionCookie;
    }
```
Thanks!

**Comment by vitorbal** [comment]
@sixnames thanks for the report! Would you mind opening a pull request to fix this?

**Comment by sixnames** [comment]
@vitorbal thank you for answer. I will try.

**Comment by sixnames** [comment]
Sorry! The problem is not in your package. It's in node-mocks-http
